url: https://sarahestetica.com
baseurl:

# Site settings
title: Sarah Estética - Natural. Orgânica. Vegana
email: contato@sarahestetica.com
description: "Centro de Estética especializado em slow beauty e tratamentos naturais. Todos os produtos utilizados são veganos, livres de agentes nocivos e sintéticos. Convidamos você para conhecer todas as possibilidades de cuidados com a pele, corpo e mente."


# Team names, titles and social links
people:
- name: Isabela Pinheiro
  pic: 1
  position: "\"Nunca fui tão bem atendida! Ambiente super confortável, atendimento impecável, amo todas as dicas e conhecimento que a Sarah passa sempre e o resultado também é incrível, nunca tive resultados tão bons com a limpeza de pele, minha pele sempre ficava muuito irritada. Não troco por nada!\""

- name: Julia Santos
  pic: 2
  position: "\"Adoro fazer peeling e limpeza de pele com a Sarah! Minha pele fica limpa e macia e não dói! Também fiz drenagem linfática e amei a massagem e me senti muito mais leve! Recomendo para todas as minhas amigas!\""

- name: Thais Nunes
  pic: 3
  position: "\"Conheço o trabalho da Sarah desde quando atendia a domicílio e posso falar com toda certeza que independente de onde esteja, seu trabalho é impecável. Lembro de ter ficado surpresa com a minha pele pós limpeza, estava linda e renovada, dava pra ver o resultado de um trabalho com amor e capricho. A conheci através de um grupo no face e não largo mais. E com o tempo vi que a Sarah é uma profissional e pessoal incrível &hearts; Preço justo pelo trabalho de qualidade.\""

- name: Daniella Origuela
  pic: 4
  position: "\"Os tratamentos são incríveis, a gente vê o resultado de verdade. Os produtos que a Sarah usa são de qualidades, com aromas relaxantes e naturais. E os preços são super justos. Eu adoro e recomendo!\""

- name: Ariane Marcinari
  pic: 5
  position: "\"A Sarah é simplesmente a DONA da minha pele, mais do que eu mesma hahaha. Um ano cuidando de mim, um ano de amizade e muito amor! Amo muito minha fadinha\""

- name: Geovana Fiamozzini
  pic: 6
  position: "\"A Sarah é incrível! Como profissional, já na primeira sessão eu percebi diminuição das minhas celulites e me senti bem menos inchada, mãos de fada! E como pessoa também, sempre puxando assunto e deixando a gente bem à vontade, queria ser amiga dela hahahaha\""

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/sarah.estetica/
  - title: facebook
    url: https://www.facebook.com/sarah.estetica1

# Postal address (add as many lines as necessary)
address:
  - line: R. Augusta, 1371 - sobreloja 209
  - line: Consolação, São Paulo - SP, 01305-100, Brasil

# Build settings
markdown: kramdown
permalink: pretty
